image: "rust:latest"

stages:
  - build
  - test
  - semgrep
  - sonarcloud


build:
  stage: build
  script:
    - cargo check
    - cargo build -r

test:
  stage: test
  script:
    - rustc --version && cargo --version 
    - cargo test --workspace --verbose

semgrep:
  stage: semgrep
  image: semgrep/semgrep
  script: semgrep ci --code
  variables:
    SEMGREP_APP_TOKEN: "$SEMGREP_APP_TOKEN"


sonarcloud:
  stage: sonarcloud
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.organization=joltedbot -Dsonar.projectKey=joltedbot_chunkdump
  variables:
    SONAR_HOST_URL: "$SONAR_HOST_URL"
    SONAR_TOKEN: "$SONAR_TOKEN"
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0" 